# Generated by Django 5.2.6 on 2025-09-07 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=50)),
                ('vin', models.CharField(blank=True, max_length=17, null=True, unique=True)),
                ('description', models.TextField(blank=True, max_length=250)),
            ],
        ),
    ]
