# Generated by Django 5.2.6 on 2025-09-09 23:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_accessory_car_user_car_accessories_servicerecord'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessory',
            old_name='category',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='car',
            name='accessories',
        ),
        migrations.AddField(
            model_name='accessory',
            name='car',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='my_app.car'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='accessory',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
